version: 2
defaults: &defaults
  working_directory: ~/project
  machine:
    - image: cimg/ruby:3.1.2
      environment:
        RAILS_ENV: test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build docker images
          command: docker-compose build
      - run:
          name: Publish docker images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose push
  rspec:
    <<: *defaults
    steps:
      - checkout
      - run: cd ~/project
      - run:
          name: Pull docker images
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose -f docker-compose.test.yml pull
      - run:
          name: Build docker compose environment
          command: docker-compose -f docker-compose.test.yml build --pull
      - run:
          name: Start docker compose environment
          command: docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Create test database
          command: docker-compose -f docker-compose.test.yml exec api bundle exec rails db:create
      - run:
          name: Load database schema
          command: docker-compose -f docker-compose.test.yml exec api bundle exec rails db:schema:load
      - run:
          name: Run RSpec
          command: |
            docker-compose -f docker-compose.test.yml exec api bundle exec rspec --format progress --format RspecJunitFormatter -o .rspec_output
      - store_test_results:
          path: ./api/.rspec_output
workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec



#      - build
#      - rspec:
#          requires:
#            - build