default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: mtgflashcards_dev

test:
  <<: *default
  database: mtgflashcards_test

production:
  <<: *default
  database: mtgflashcards
  password: <%= ENV['POSTGRES_PASSWORD'] %>